### ISSUE TITLE
Wilkinson Algorithm for Beeswarm Layout

### ISSUE THREAD

**Issue by TheCedarPrince** [asinghvi17/SwarmMakie.jl#5]
Another algorithm that could be used for beeswarm plots is the one originally described in [_Dot Plots_ by Leland Wilkinson](https://www.cs.uic.edu/~wilkinson/Publications/dotplots.pdf). @asinghvi17 and I found an initial sketch started by @jkrumbiegel in https://github.com/MakieOrg/Makie.jl/issues/1950#issuecomment-1129154072 

Starting to explore this implementation a bit further with commit https://github.com/asinghvi17/SwarmMakie.jl/commit/4a96193ec6ef6b03ac0fdb82a0bfd3a442610d42 and see how it also works for layouting of a swarm plot.

**Comment by TheCedarPrince** [comment]
Ah that's a fair point @asinghvi17 -- I was thinking more of supporting this figure for the dot plot paper: 
![image](https://github.com/asinghvi17/SwarmMakie.jl/assets/29561456/4f8eae4b-4936-4daf-b2e9-967ae1399ddc)

> We could implement that, even using this framework, but I'm not too sure that it's a good fit here.

That's very fair! I could remove the Wilkinson algorithm from the repo and we can carry on -- what do you want to call here?

**Comment by asinghvi17** [comment]
Hmm I think I see what you're saying - Instead of preserving the exact y coordinate, we would snap the y coordinate to the bin grid?  That makes sense and would be a pretty useful method, IMO.

**Comment by TheCedarPrince** [comment]
Exactly!
